//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationClient.ServiceReferenceFlipCase {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringData", Namespace="http://schemas.datacontract.org/2004/07/FlipCaseService")]
    [System.SerializableAttribute()]
    public partial class StringData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlippedCaseStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlippedCaseString {
            get {
                return this.FlippedCaseStringField;
            }
            set {
                if ((object.ReferenceEquals(this.FlippedCaseStringField, value) != true)) {
                    this.FlippedCaseStringField = value;
                    this.RaisePropertyChanged("FlippedCaseString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalString {
            get {
                return this.OriginalStringField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalStringField, value) != true)) {
                    this.OriginalStringField = value;
                    this.RaisePropertyChanged("OriginalString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFlipCase.IFlipCaseService")]
    public interface IFlipCaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlipCaseService/FlipTheCase", ReplyAction="http://tempuri.org/IFlipCaseService/FlipTheCaseResponse")]
        ConsoleApplicationClient.ServiceReferenceFlipCase.StringData FlipTheCase(ConsoleApplicationClient.ServiceReferenceFlipCase.StringData sd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlipCaseService/FlipTheCase", ReplyAction="http://tempuri.org/IFlipCaseService/FlipTheCaseResponse")]
        System.Threading.Tasks.Task<ConsoleApplicationClient.ServiceReferenceFlipCase.StringData> FlipTheCaseAsync(ConsoleApplicationClient.ServiceReferenceFlipCase.StringData sd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlipCaseServiceChannel : ConsoleApplicationClient.ServiceReferenceFlipCase.IFlipCaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlipCaseServiceClient : System.ServiceModel.ClientBase<ConsoleApplicationClient.ServiceReferenceFlipCase.IFlipCaseService>, ConsoleApplicationClient.ServiceReferenceFlipCase.IFlipCaseService {
        
        public FlipCaseServiceClient() {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlipCaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplicationClient.ServiceReferenceFlipCase.StringData FlipTheCase(ConsoleApplicationClient.ServiceReferenceFlipCase.StringData sd) {
            return base.Channel.FlipTheCase(sd);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplicationClient.ServiceReferenceFlipCase.StringData> FlipTheCaseAsync(ConsoleApplicationClient.ServiceReferenceFlipCase.StringData sd) {
            return base.Channel.FlipTheCaseAsync(sd);
        }
    }
}
